#!/usr/bin/env python3
# Generate bin/spec_tables.inc (tables for src/spectrum.s) from tests/spec_model.py, so asm and model share them.
import os, sys
here = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, os.path.join(here, '..', 'tests'))
from spec_model import SIN, LT, COLS, CSPLIT, MARKS
import struct
SINT_ADDR = 0x400aefe8          # data area after COLH/PK (reclaimed song-popup space); written by patch_section3.py
open(os.path.join(here, '..', 'bin', 'spec_sin.bin'), 'wb').write(b''.join(struct.pack('>h', v) for v in SIN))
out = ["| generated by tools/gen_spec_tables.py - do not edit",
       "    .set CSPLIT, %d" % CSPLIT,
       "    .set SINT, 0x%08x        | 257 x int16 quarter sine (bin/spec_sin.bin)" % SINT_ADDR,
       "    .balign 2"]
out += ["COLT:"] + ["    .short " + ", ".join(str(lo | (n << 10)) for lo, n in COLS[i:i + 16]) for i in range(0, 128, 16)]
out += ["LTT:", "    .byte " + ", ".join(str(v) for v in LT), "MARKT:", "    .byte " + ", ".join(str(v) for v in MARKS), "    .balign 2"]
open(os.path.join(here, '..', 'bin', 'spec_tables.inc'), 'w').write("\n".join(out) + "\n")
