#!/usr/bin/env python3
"""Tables for the Digi utilities master EQ (mods/digiutils/eq.c) -> mods/digiutils/eq_tables.h.

    python3 tools/gen_eq_tables.py

Everything the fixed-point code needs that would take floating point on the unit (no FPU):
  G27[128]    g = tan(pi f / 48000) in Q27, f = 20 Hz * 1000^(i/127) (the knob's 128 frequency steps)
  HZ[128]     f rounded, for the display
  A27[49]     A = 10^(dB/40) in Q27, dB = (i - 24) / 2 (-12 .. +12 dB in 0.5 dB steps); 1/A = A27[48 - i]
  SQA27[49]   sqrt(A) = 10^(dB/80) in Q27
  AA27[49]    A^2 = 10^(dB/20) in Q27 (also the output level)
  K27[16]     k = 1/Q in Q27, Q = 0.3 * (8/0.3)^(i/15)
  QX10[16]    Q * 10, for the display
  WQ8[16]     half-width (in knob steps x 256) of a bell's drawn curve at that Q
  COLF8[128]  knob-step position (x 256) of each spectrum column (30 Hz .. 20 kHz, log)
  LOG2Q8[256] log2(1 + i/256) x 256, for the drawn response curve
The model (tests/eq_model.py) imports the same functions, so both sides use identical numbers.
"""
import math, os

FS = 48000.0
NF, NG, NQ = 128, 49, 16
K2_27 = int(round(math.sqrt(2) * (1 << 27)))        # shelves: Q = 1/sqrt(2)


def freq(i):
    return 20.0 * 1000.0 ** (i / (NF - 1))


def qval(i):
    return 0.3 * (8.0 / 0.3) ** (i / (NQ - 1))


def db(i):
    return (i - 24) / 2.0


def q27(x):
    return int(round(x * (1 << 27)))


def tables():
    t = {}
    t["G27"] = [q27(math.tan(math.pi * freq(i) / FS)) for i in range(NF)]
    t["HZ"] = [int(round(freq(i))) for i in range(NF)]
    t["A27"] = [q27(10 ** (db(i) / 40)) for i in range(NG)]
    t["SQA27"] = [q27(10 ** (db(i) / 80)) for i in range(NG)]
    t["AA27"] = [q27(10 ** (db(i) / 20)) for i in range(NG)]
    t["K27"] = [q27(1.0 / qval(i)) for i in range(NQ)]
    t["QX10"] = [int(round(qval(i) * 10)) for i in range(NQ)]
    steps_per_oct = (NF - 1) / math.log2(1000.0)
    w = []
    for i in range(NQ):
        q = qval(i)
        r = (1.0 / q + math.sqrt(1.0 / q ** 2 + 4.0)) / 2.0        # half-gain point of a bell (dB)
        w.append(int(round(math.log2(r) * steps_per_oct * 256)))
    t["WQ8"] = w
    col = []
    for c in range(128):                                          # spectrum page: 30 Hz .. 20 kHz, log
        f = 30.0 * (20000.0 / 30.0) ** (c / 127.0)
        col.append(int(round(math.log(f / 20.0) / math.log(1000.0) * (NF - 1) * 256)))
    t["COLF8"] = col
    t["LOG2Q8"] = [int(round(256 * math.log2(1 + i / 256.0))) for i in range(256)]
    return t


def main():
    t = tables()
    out = ["/* generated by tools/gen_eq_tables.py - do not edit */", "#define EQ_K2_27 %d" % K2_27]
    kinds = {"HZ": "unsigned short", "QX10": "unsigned char", "LOG2Q8": "unsigned char"}
    for name, vals in t.items():
        typ = kinds.get(name, "int")
        out.append("static const %s %s[%d] = {" % (typ, name, len(vals)))
        for i in range(0, len(vals), 8):
            out.append("    " + ", ".join(str(v) for v in vals[i:i + 8]) + ",")
        out.append("};")
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    p = os.path.join(root, "mods", "digiutils", "eq_tables.h")
    open(p, "w").write("\n".join(out) + "\n")
    print("wrote", p)


if __name__ == "__main__":
    main()
